language: node_js
node_js:
  - "14"

jobs:
  include:
    - stage: SAST Check
      script:
        - echo "Preparing for SAST Scan..."
        - echo "Initiating SAST scan. Please wait..."
        - |
          RESPONSE=$(curl -s -X POST \
            -H "Client-ID: $INTRUCEPT_CLIENT_ID" \
            -H "Client-Secret: $INTRUCEPT_CLIENT_SECRET" \
            -F "projectZipFile=@project.zip" \
            -F "applicationId=$INTRUCEPT_APPLICATION_ID" \
            -F "scanName=Csharp Dvcsharp SAST Scan - $TRAVIS_COMMIT" \
            -F "language=c#" \
            https://appsecops-api.intruceptlabs.com/api/v1/integrations/sast-scans)
          
          echo "SAST scan completed."
          VULNS_TABLE=$(echo "$RESPONSE" | jq -r '.vulnsTable')
          echo "Vulnerabilities Table:"
          echo "$VULNS_TABLE"

    - stage: SCA Check
      script:
        - echo "Preparing for SCA Scan..."
        - echo "Initiating SCA scan. Please wait..."
        - |
          RESPONSE=$(curl -s -X POST \
            -H "Client-ID: $INTRUCEPT_CLIENT_ID" \
            -H "Client-Secret: $INTRUCEPT_CLIENT_SECRET" \
            -F "projectZipFile=@project.zip" \
            -F "applicationId=$INTRUCEPT_APPLICATION_ID" \
            -F "scanName=Csharp Dvcsharp SCA Scan - $TRAVIS_COMMIT" \
            -F "language=c#" \
            https://appsecops-api.intruceptlabs.com/api/v1/integrations/sca-scans)
          
          echo "SCA scan completed."
          VULNS_TABLE=$(echo "$RESPONSE" | jq -r '.vulnsTable')
          echo "Vulnerabilities Table:"
          echo "$VULNS_TABLE"
