language: node_js
node_js:
  - "14"

jobs:
  include:
    - stage: SAST Check
      script:
        - exec 2>&1
        - |
          printf "Preparing for SAST Scan...\n"
          printf "Initiating SAST scan. Please wait...\n"
          RESPONSE=$(curl -s -X POST \
            -H "Client-ID: $INTRUCEPT_CLIENT_ID" \
            -H "Client-Secret: $INTRUCEPT_CLIENT_SECRET" \
            -F "projectZipFile=@project.zip" \
            -F "applicationId=$INTRUCEPT_APPLICATION_ID" \
            -F "scanName=Csharp Dvcsharp SAST Scan - $TRAVIS_COMMIT" \
            -F "language=c#" \
            https://appsecops-api.intruceptlabs.com/api/v1/integrations/sast-scans)
          
          printf "\nSAST scan completed.\n"
          VULNS_TABLE=$(echo "$RESPONSE" | jq -r '.vulnsTable')
          printf "Vulnerabilities Table:\n"
          echo "$VULNS_TABLE"

    - stage: SCA Check
      script:
        - exec 2>&1
        - |
          printf "Preparing for SCA Scan...\n"
          printf "Initiating SCA scan. Please wait...\n"
          RESPONSE=$(curl -s -X POST \
            -H "Client-ID: $INTRUCEPT_CLIENT_ID" \
            -H "Client-Secret: $INTRUCEPT_CLIENT_SECRET" \
            -F "projectZipFile=@project.zip" \
            -F "applicationId=$INTRUCEPT_APPLICATION_ID" \
            -F "scanName=Csharp Dvcsharp SCA Scan - $TRAVIS_COMMIT" \
            -F "language=c#" \
            https://appsecops-api.intruceptlabs.com/api/v1/integrations/sca-scans)
          
          printf "\nSCA scan completed.\n"
          VULNS_TABLE=$(echo "$RESPONSE" | jq -r '.vulnsTable')
          printf "Vulnerabilities Table:\n"
          echo "$VULNS_TABLE"
